services:
  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: 1234
      # MONGO_INITDB_DATABASE: sample_db
    volumes:
      - mongo_data:/data/db
      # - ./init.d:/docker-entrypoint-initdb.d
      - ./samples:/tmp/samples
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')",
          "--quiet",
          # "--username=root",
          # "--password=1234",
          # "--authenticationDatabase=admin"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      # ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_MONGODB_PORT: 27017
      # Если эту опцию сделать false, то express запросит имя пользователя
      # и пароль. По умолчанию это admin и pass
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

      # ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: pass

      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      
    depends_on:
      - mongo
    restart: always

volumes:
  mongo_data:
