services:
  clickhouse:
    image: yandex/clickhouse-server:22.1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      # - clickhouse_data:/var/lib/clickhouse
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_DB=nyc_taxi
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

# volumes:
#   clickhouse_data:
